### ISSUE TITLE
ModuleNotFoundError: No module named 'pytz', Dependencies already installed, skipping installation.

### ISSUE THREAD

**Issue by MadSaint777** [sizifart/MiniGames-Autoclicker-Bot#2]
Requirement already satisfied: pytz in c:\users\user\minigames-autoclicker-bot\venv\lib\site-packages (2024.1)

============================================================================
[cexio     ] [ERROR] | Traceback (most recent call last):
[cexio     ] [ERROR] |   File "C:\Users\User\MiniGames-Autoclicker-Bot\bots\cexio\cexio.py", line 11, in \<module\>
[cexio     ] [ERROR] |     from bot.tapper import run_tapper
[cexio     ] [ERROR] |   File "C:\Users\User\MiniGames-Autoclicker-Bot\bots\cexio\bot\tapper.py", line 7, in \<module\>
[cexio     ] [ERROR] |     import pytz
[cexio     ] [ERROR] | ModuleNotFoundError: No module named 'pytz'
[goats     ] | 2024-10-18 14:43:23 | INFO     | 190  | 0240       | Successful login...
[goats     ] | 2024-10-18 14:43:23 | INFO     | 194  | 0240       | Age: 2 | Balance: 3486
[cexio     ] [ERROR] | Traceback (most recent call last):
[cexio     ] [ERROR] |   File "C:\Users\User\MiniGames-Autoclicker-Bot\bots\cexio\cexio.py", line 11, in \<module\>
[cexio     ] [ERROR] |     from bot.tapper import run_tapper
[cexio     ] [ERROR] |   File "C:\Users\User\MiniGames-Autoclicker-Bot\bots\cexio\bot\tapper.py", line 7, in \<module\>
[cexio     ] [ERROR] |     import pytz
[cexio     ] [ERROR] | ModuleNotFoundError: No module named 'pytz'

**Comment by MadSaint777** [comment]
I run from administrator.
All work

**Comment by MadSaint777** [comment]
I run from administrator.
All work
